project:
  type: website
  output-dir: docs

website:
  title: "PLUMY- Protecting LQBTQ+ Underserved Miami-Dade Youth"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:aboutus
      - href: "https://docs.google.com/forms/d/e/1FAIpQLSeJkbSPI3s2-otQp89Hxh5x9EbbRV2aM5ER2xRChpcwprVFQQ/viewform?usp=sf_link"
        text: Join
      
      
  sidebar:   
    - id: aboutus
      title: "About"
      href: about.qmd
      style: "docked"
      collapse-level: 2
      contents: 
        - title: "Our Mission"
        - href: about.qmd
        - title: "Our Staff"
        - href: staff.qmd
        

format:
  html:
    theme:
      light: journal
      dark: cyborg
    css: styles.css
    toc: true

editor: visual


