project:
  type: website
  output-dir: docs

website:
  title: "PLUMY: Protecting LQBTQ+ Underserved Miami-Dade Youth"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About Us
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

