project:
  type: website
  output-dir: docs

website:
  title: "PLUMY- Protecting LQBTQ+ Underserved Miami-Dade Youth"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:aboutus
      - href: resources.qmd
        text: Resources
      - href: "https://docs.google.com/forms/d/e/1FAIpQLSeJkbSPI3s2-otQp89Hxh5x9EbbRV2aM5ER2xRChpcwprVFQQ/viewform?usp=sf_link"
        text: Join
      
  sidebar:   
    - id: aboutus
      title: "About"
      href: about.qmd
      style: "docked"
      collapse-level: 2
      contents: 
        - title: "Our Mission"
        - href: about.qmd
        - title: "Our Staff"
        - href: staff.qmd
  page-footer:  
    left: |
      PLUMY Protecting LGBTQ Underserved Miami Dade Youth Corp. (EIN: 92-3722243) is a tax-exempt non-profit organization under Internal Revenue Code (IRC) section 501(c)(3). 

        

format:
  html:
    theme:
      light: journal
      dark: cyborg
    css: styles.css
    toc: true
    grid: 
      sidebar-width: 200px
      body-width: 1340px
      margin-width: 200px

editor: visual

title-block-banner: true 


